- name: Edit banner
  hosts: all
  gather_facts: no
  connection: network_cli
  collections:
    - cisco.ios

  tasks:
    - name: change banner
      ios_config:
        lines:
          - banner motd ^hello, welcome^
      become: yes
      become_method: enable
