- name: Edit loopback
  hosts: all
  gather_facts: no
  connection: network_cli
  collections:
    - cisco.ios

  tasks:
    - name: change loopback addr
      ios_config:
        lines:
          - interface Loopback0
          - ip address {{ loopback_ip }} 255.255.255.255
      become: yes
      become_method: enable
